Fantom-foundation/Sonic

cmd/sonictool/chain/import_events.go
config/config_custom_test.go
config/defaults.go
go.mod
go.sum

* Add Discovery fix https://github.com/Fantom-foundation/go-ethereum-substate/pull/56
* Disable DiscoveryV4 by default
* Deprecated NoUSB flag not set anymore during events import (avoid deprecation warning)

Fix DiscoveryV5 and disable DiscoveryV4 by default

---

gossip/evmstore/store.go

While Sonic stops, there is no indication why the client is so long idle. Adding log message letting the user know about the state-db closing in progress.
```
INFO [05-15|17:36:10.631] Stopping Fantom protocol 
INFO [05-15|17:36:10.632] Fantom protocol stopped 
INFO [05-15|17:36:10.633] Fantom service stopped 
INFO [05-15|17:36:10.633] Closing State DB...                      module=evm-store
INFO [05-15|17:36:10.855] State DB closed                          module=evm-store
```

Add log message before Carmen close

---

ethapi/api.go
gossip/filters/api.go

This extends RPC api to never return a null Topics field in the getLogs / getTransactionReceipt responses.

Avoid null topics in logs in RPC

---

cmd/sonictool/chain.go
cmd/sonictool/chain/export_genesis.go
cmd/sonictool/chain/import_events.go
go.mod
go.sum
opera/genesisstore/disk.go

Adds a fully compatible replacement for the standard "compress/gzip" library. The newly added dependency allows parallel compression/decompression of the genesis files. See [https://github.com/klauspost/pgzip](https://github.com/klauspost/pgzip) for a reference and performance benchmarks.

Add multi-threaded gzip compression/decompression

---

cmd/sonictool/db/dbutils.go
cmd/sonictool/genesis/import.go

When the database is already initialized, avoid overriding it by the sonictool genesis tool:
```
sonictool --datadir=/tmp/opera genesis fake 1
database in datadir is already initialized: database directories 'chaindata' and 'carmen' already exists
```
When any of the carmen or chaindata directories are missing, the database is supposed to be corrupted, directories are removed and recreated from the genesis file.

Avoid overriding already initialized datadir

---

gossip/service.go
vecmt/backed_map.go
vecmt/index.go
vecmt/vecflushable.go

This adds a cache into dagIndexer's VecFlushable.
The cache has been removed to resolve issue #85 - the cache have not been flushed correctly on the node shutdown, which resulted in occasional database breaking on shutdown.
This PR re-introduce the cache with proper closing (flushing of the backedMap into the epoch db).

Re-add dagIndexer cache (with proper closing)

---

ethapi/api.go
ethapi/backend.go
evmcore/dummy_block.go
gossip/ethapi_backend.go
gossip/filters/api.go
gossip/filters/filter_system.go

The block/header JSON serialization is duplicated between ethapi (regular RPC queries) and filters (handling of `eth_subscribe(newHeads)`) - this moves this serialization into a single place and ensures the same format for both.

Refactor block/header serialization in RPC - remove duplicite code

---

go.mod
go.sum

Upgrade Carmen to the latest main to include changes improving the shutdown time.

Upgrade carmen, improve node shutdown time

---

go.mod
go.sum

This upgrades carmen to include https://github.com/Fantom-foundation/Carmen/pull/949 - disabling problematic background flushing.

Upgrade carmen, disable node flusher

---

go.mod
go.sum

Carmen versions after the background flushing integration are considered unsafe - reverting to the safe version which passed successful full-history run on Jenkins as suggested by @HerbertJordan.

Revert Carmen upgrade - use version before background flushing

---

ethapi/api.go

Fixing wrong reference of block header from parent to actual block which is replayed by debug_trace
Issue https://github.com/Fantom-foundation/Sonic/issues/180

Fix parent block header reference

---

gossip/evmstore/statedb.go

This should fix issue #179 - impossibility to trace block 1.
Tracing is unable to obtain starting state of the block 1, which is the StateRoot of block 0. However blocks db returns zero stateRoot for the block 0. Carmen knows the correct state, but it is not unable to verify it against the blocks db. This add exception for the block 0 into the check.

Fix tracing of block 1 - ignore missing stateRoot of block 0 in blocks db

---

ethapi/api.go
go.mod
go.sum
gossip/evmstore/carmen.go
inter/state/adapter.go

This adds support of eth_getProof/ftm_getProof method into the RPC interface.
~**To be done:** replace working version of carmen with the main branch when https://github.com/Fantom-foundation/Carmen/pull/975 merged.~

Add support of ftm_getProof RPC method

---

cmd/sonictool/check/archive.go
ethapi/api.go
ethapi/tx_trace.go
evmcore/state_processor.go
go.mod
go.sum
gossip/evmstore/carmen.go
gossip/evmstore/statedb_import.go
gossip/evmstore/statedb_verify.go
integration/makegenesis/genesis.go

From review in https://github.com/Fantom-foundation/Sonic/pull/187 it seems the Carmen upgrade and related migration from big.Int amounts to Carmen specific Amount type would be better to do in a standalone PR.
Because of the conversion, StateDB can now produce error which can be exported only through dedicated Error() method. Then we need to make sure this method is called after EVM run.

Upgrade carmen to version with Amount type

---

go.mod
go.sum

Fix for closing all rpc connections while shuting down node as described in this [PR](https://github.com/Fantom-foundation/go-ethereum-substate/pull/63)
Solves https://github.com/Fantom-foundation/Sonic/issues/191

Update go-ethereum-substate version

---

config/flags/flags.go
ethapi/api.go
ethapi/limit.go
ethapi/tx_trace.go
gossip/config.go
gossip/service.go

This PR adds configurable limit for RPC response size for namespace debug and trace.
Limit can be configured with CLI parameter:
- rpc.maxresponsesize
Or with config file variable:
- MaxResponseSize
Size is set in bytes and default for this variable is set to 25MB

Add RPC response size limit for debug and trace namespace

---

ethapi/tx_trace.go

When using "latest" and "pending" in RPC call for tracing block and tracing filter, it was not correctly translated to a block number. This PR fixes this.

Handle latest and pending options for trace namespace call

---

go.mod
go.sum

Carmen version [95f776f](https://github.com/Fantom-foundation/Carmen/commit/95f776fc98c831d198c14a96130b69c76999adbc) may be extremely slow when running in archive mode.
Upgrading to fixed version, which has passed the full archive recording test.

Upgrade Carmen to 7f258ce to avoid too often checkpoints

---

.github/workflows/test_build.yml

This PR updates the github workflow file processing incoming pull requests by eliminating the automated upload of the `opera` binary.
Since the Sonic migration, the `opera` binary is not actually created any more. However, recently this final upload step started to fail because of the out-dated version of the upload script (see [Deprecation notice](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)).

Remove automated publishing of opera client

---

go.mod
go.sum

After this Carmen fix the healing of broken database succeed (after 5-6 hours) on my testing server (32GB ram):
The CPU usage was high, so probably this can be faster when more CPU cores is used.
```
root@jk-sonic-testing-heal-small2:~# GOMEMLIMIT=20000 sonictool --cache 8000 --datadir=/var/sonic/mainnet heal
INFO [09-19|17:48:13.007] Maximum peer count                       total=50
INFO [09-19|17:48:13.008] Healing gossip db...
INFO [09-19|17:48:13.121] Last closed epoch with available state found epoch=298029
INFO [09-19|17:48:13.122] Reverting to epoch state                 epoch=298029 block=88051672
INFO [09-19|17:48:13.127] Removing excessive events
INFO [09-19|17:48:13.468] Removing epoch DBs - will be recreated on next start
INFO [09-19|17:48:13.468] Removing epoch db …
```

Upgrade carmen to to include healing fix

---

example-genesis.json
integration/makefakegenesis/json.go

This modifies the genesis.json file format to allow setting all network rules from the json file.
It also unifies the json structure with the other network rules serialization - like the `ftm_getRules` output.

Allow setting all network rules in genesis.json

---

gossip/ethapi_backend.go

For RPC request
```
{"jsonrpc":"2.0","method":"dag_getEvent","params":["invalid"],"id":1}
```
the Sonic client fails:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"method handler crashed"}}
```
and prints stacktrace into the log.
This fix handles the invalid input better:
```
{"jsonrpc":"2.0","method":"dag_getEvent","params":["invalid"],"id":1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"full hash parsing error: hex string without 0x prefix"}}
```

Handle dag_getEvent panic on invalid input

---

cmd/sonicd/launcher.go
config/flags/flags.go
config/node_config.go
ethapi/api.go
ethapi/tx_trace.go
evmcore/evm.go
evmcore/state_processor.go

* Add import of tracers to register them
* Add `rpc.batch-request-limit` and `rpc.batch-response-max-size` flags (limits supported by new ethereum)
* Fix StateDB usage in tracing (WrapStateDbWithLogger usage)
*  Include fix #194
* Always set block number/block hash into the EVM in tracing
* Resolve todo for blobs of internal txs (probably not going to be used ever, but better to have it consistent)

Include tracing fixes

---

config/make_node.go
gossip/c_block_callbacks.go

Fixes #218.
Add following prometheus metrics, used in Norma testing:
* `chain_execution_nonresetting` - because original `chain_execution` metrics is being reset regularly in the new ethereum, I am adding the original non-resetted metrics as a new metric.
* `chain_info` metrics added in the new ethereum made working by setting the chain_id into it
```
chain_info {chain_id="4003"} 1
chain_execution_count 1
chain_execution {quantile="0.5"} 151768
chain_execution {quantile="0.75"} 151768
chain_execution {quantile="0.95"} 151768
chain_execution {quantile="0.99"} 151768
chain_execution {quantile="0.999"} 151768
chain_execution {quantile="0.9999"} 151768
chain_execution_nonresetting_count 9
chain_execution_nonresetting {quantile="0.5"} 138109
chain_execution_nonresetting {quantile="0.75"} …
```

Add missing prometheus metrics

---

ethapi/api.go
eventcheck/epochcheck/epoch_check.go
evmcore/tx_pool.go
evmcore/tx_pool_test.go

This PR adds validation of the EIP-4844 blob transaction on the transaction pool level. If the blob transaction is not empty, it is not accepted by the transaction pool.
Because this PR is dependant on correct upgrade handling, PR https://github.com/Fantom-foundation/Sonic/pull/216 needs to be merged before this PR

Don't accept non empty blob transactions

---

cmd/sonictool/app/main.go
config/config.go
config/flags/flags.go
go.mod
go.sum

This PR introduces a new flag used only for `events import` subcommand that instructs Lachesis to suppress the frame check panic. This may be useful for regression testing where the monotonicity fix from https://github.com/Fantom-foundation/lachesis-base-sonic/pull/3 is not important and could obstruct ingestion of historical data.

Suppress panic flag for event file importing

---

gossip/emitter/emitter_test.go
gossip/emitter/parents.go
gossip/emitter/parents_test.go

This PR makes all genesis events not have any parents. Having a parent by other creator as a genesis turns out to be problematic due to Lachesis' iterative frame calculation, thus inducing frame non-monotonicity for the event chains. Such non-monotonicity makes future incrementalization efforts impossible and potentially hides other performance and security concerns.

Empty parents for genesis events and parents tests

---

ethapi/api.go
tests/basefee_test.go
tests/contracts/basefee/basefee.go
tests/contracts/basefee/basefee.sol
tests/contracts/basefee/gen.go

This PR adds a end-to-end test for the BaseFee opcode ([EIP-3198](https://eips.ethereum.org/EIPS/eip-3198)).
The test added by this PR performs the following steps:
- deploys a smart contract capable of retrieving the current basefee for head and archive queries
- fetches the basefee from the contract using a transaction (via a log message)
- fetches the basefee from the block header of the block containing the transaction
- fetches the basefee from the archive using another method of the contract
- checks that the basefee is not zero and all sources report the same value
By implementing this test, an issue when running queries on the archive was detected. For all queries, the base-fee was set to zero. A fix for this issue is part of this PR.
This PR is part of …

Add end-to-end BaseFee instruction test

---

tests/state_test.go

This PR updates ethereum tests to create temp directory by `os.MkdirTemp` instead of standard `t.TempDir`. The reason is that ethereum tests produce extensively long names of tests. When `t.TempDir` is called on such a test, it fails on `file name too long` e.g.:
```
19:02:15                  state_test.go:71: TempDir: mkdir /tmp/TestStatePyspecscancuneip4844_blobspoint_evaluation_precompile_external_vectors.jsonsrcGeneralStateTestsFillerPyspecscancuneip4844_blobstest_point_evaluation_precompile.pytest_point_evaluation_precompile_external_vectorsfork_Cancun-state_test-versioned_hash_None-verify_kzg_proof_case_correct_proof_83e53423a2dd93feCancun03556998538: file name too long
```

changes tmp dir creation to avoid too long names

---

cmd/sonictool/chain/import_events.go
eventcheck/heavycheck/heavy_check.go
opera/genesisstore/disk.go
valkeystore/encryption/encryption.go

This PR replaces uses of `Compare !=0` with `!bytes.Equal`.
Doing so is not only more idiomatic, but potentially faster. 
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint: Replace uses of bytes.Compare with bytes.Equal

---

ethapi/api.go
evmcore/dummy_block.go

This PR adds an RPC function eth_blobBaseFee
For now, it only returns 1 as blobs are not implemented in Sonic client
As blobs are not supported yet, blob base fee is equal to min blob gas price, because calculation of blob base fee is based on the blob gas price and excess blob gas which is always 0

Add eth_blobBaseFee RPC function

---

tests/contracts/transientstorage/gen.go
tests/contracts/transientstorage/transientstorage.go
tests/contracts/transientstorage/transientstorage.sol
tests/transientstorage_test.go

This PR adds integration test for Transient Storage opcode ([EIP-1153](https://eips.ethereum.org/EIPS/eip-1153))
The test added performs the following steps:
deploys a smart contract capable of interacting with inner contract
inner contract implements transient variable which is set and obtained within same transaction thru main contract
main contract emits obtained value of transient variable of inner contract
checks, if the value stored during transaction and emited as log is not 0 
checks, if obtaining this value outside store function always returns 0
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/22

Add Transient Storage integration test

---

gossip/c_block_callbacks.go

The following code may access the variable `e` member functions when being `nil`
```
e := store.GetEventPayload(id)
if e == nil {
log.Crit("Block event not found", "event", id.String())
}
fullEvents[i] = e
gasPowerUsedSum += e.GasPowerUsed()    // <= nil access
```
part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint, Prevent use of nil variable

---

evmcore/evm.go
tests/blobbasefee_test.go
tests/contracts/blobbasefee/blobbasefee.go
tests/contracts/blobbasefee/blobbasefee.sol
tests/contracts/blobbasefee/gen.go

This PR adds an end-to-end test for BlobBaseFee opcode ([EIP-7516](https://eips.ethereum.org/EIPS/eip-7516))
The test added performs the following steps:
- deploys a smart contract capable of retrieving the current blobbasefee for archive queries
- fetches the blobbasefee from the contract using a transaction (via a log message)
- fetches the blobbasefee from the archive using another method of the contract
- checks that the blobbasefee is zero and all sources report the same value. We compare to zero because BlobBaseFee is currently not supported by go-ethereum-sonic
This PR is part of [#10](https://github.com/Fantom-foundation/sonic-admin/issues/10)

Add end-to-end BlobBaseFee instruction test

---

go.mod
go.sum

This PR is updating the Tosca dependency to its current main branch. 
With all the substates, ethereum tests, unit/integration tests and CT passing, there should only be minor changes to the used LFVM before the release.

Update tosca dependency

---

evmcore/state_processor_test.go

This PR adds error handling to a unit test where an error was quietly swallowed before.

Cleanup error handling in ApplyTransaction unit test

---

evmcore/tx_pool_test.go
gossip/dummy_tx_pool.go
gossip/store.go

This PR fixes three race conditions found in unit tests. 
The first 2 issues affected exclusively testing code.
The last commit is a fix for a race condition in gossip/store:
The error can be reproduced in the develop branch with the command: `go test -race  -run ^TestBaseFee_CanReadBaseFeeFromHeadAndBlockAndHistory$ ./tests -v`.
- Last modification timestamp is accessed concurrently
- There is an unused group of mutexes (one as in HEAD but more in the past)  which have not been used for a long time (more than 2 years in history of the repo, dead code on every commit). This struct has been deleted in this PR. 
I do not discard other race conditions arising, therefore it is convenient to merge this PR asap to enable CI tests similar to …

Fix race conditions found in unit tests. 

---

cmd/sonicd/app/launcher.go
config/flags/flags.go

Adding the suppression flag to client run command to be used in testing when syncing over the network, which same as importing the event files, results in historical events being indexed and checked, thus requiring the frame panic suppression for the `sonicd` command.
Flag grouping and introducing is inconsistent between `sonictool` and `sonicd` so I decided to group it with test flags as it's exclusively used for regression testing. Let me know if something else makes more sense.

Make `suppress-frame-panic` flag available for `sonicd`

---

gossip/handler.go
utils/dbutil/threads/pool_test.go

When passing an object by value, content member variables are copied into a new memory address. This includes the content of a mutex lock, effectively cloning the mutex into a new instance. 
This PR introduces fixes for two scenarios detected, where mutexes are being copied. 
Part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint: Prevent copy of mutexes

---

tests/address_access_test.go
tests/contracts/access_cost/access_cost.go
tests/contracts/access_cost/access_cost.sol
tests/contracts/access_cost/gen.go
tests/integration_test_net.go
tests/integration_test_net_test.go

Verify warm COINBASE address [EIP-3651](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3651.md)
The tests check that the address returned is Zero, and that the access to such address is considered warm. This is done by comparing the costs of cold/warm accesses.
In addition to COINBASE, the ORIGIN instruction is tested. 
The test is written with the following structure to minimize the number of test-nets initialized:
```
--- PASS: TestAddressAccess (12.23s)
--- PASS: TestAddressAccess/coinbase_yields_zero_address (0.00s)
--- PASS: TestAddressAccess/access_is_warm (2.13s)
--- PASS: TestAddressAccess/access_is_warm/coinbase (0.64s)
--- PASS: TestAddressAccess/access_is_warm/origin (0.74s)
--- PASS: TestAddressAccess/access_is_warm/access_list (0.75s)
PASS
```
This way, the overhead of …

Integration test: Verify warm COINBASE address (EIP-3651)

---

Makefile
staticcheck.conf

This PR adds a script to run code linting from the make command: make lint
This command analyzes the code using [staticcheck](https://staticcheck.dev/) and [errcheck](https://github.com/kisielk/errcheck).
The execution of this command is not supposed to yield a satisfactory execution, as the code is currently containing some issues. For this reason, this script is not yet included in any CI nor nightly testing pipelines.
This PR is part of https://github.com/orgs/Fantom-foundation/projects/18/views/1?pane=issue&itemId=83653545&issue=Fantom-foundation%7Csonic-admin%7C25

Build: Add linting automation

---

cmd/cmdtest/test_cmd.go
evmcore/tx_pool_test.go
gossip/filters/filter_test.go
opera/genesisstore/fileshash/filehash_test.go
utils/dbutil/compactdb/keys_test.go
utils/file.go
valkeystore/encryption/encryption.go
valkeystore/encryption/io.go
valkeystore/encryption/migration.go
valkeystore/files_test.go

This PR removes the use of `ioutils`.
- `ioutil` replaced with a mix of `io` and `os`  symbols. [notes](https://stackoverflow.com/questions/75206234/for-go-ioutil-readall-ioutil-readfile-ioutil-readdir-deprecated)
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint: Remove use of deprecated standard tools.

---

tests/state_test.go

This PR switches EVM to LFVM for ethereum tests. 
Furthermore, it adds a list of blacklisted forks that are not supported by LFVM

enables lfvm in eth-tests

---

gossip/tx_scrambler_test.go

This PR fixes incorrectly constructed tests.
Thanks to @LuisPH3 we found that the condition in the test (`hasDuplicateAddresses != hasDuplicateAddresses`) actually tests nothing.
Fixing this condition revealed that the `analyseEntries` removed the entries before the address comparsion happened - the hashes were always same.

Fix incorrect test

---

gossip/evm_state_reader.go
gossip/gasprice/gasprice.go
gossip/gasprice/gasprice_test.go
gossip/service.go

This PR fixes a race condition in the initialization of the gas-price oracle.
The backend used by the oracle is set as part of the startup procedure of the main sonic server service. However, at this point HTTP service handler may already access the oracle through RPC queries, constituting a race condition.
With this fix, the backend for the gas price oracle is set during construction time.

Fix race condition in gas-price oracle startup

---

.github/workflows/test_build.yml
Jenkinsfile
Makefile

This PR enables linting as part of the PR verification. 
- go vet will be run unconstrained. 
- staticcheck will run with two ignored rules: defined in `staticcheck.conf` 
```
"-ST1005", # error string formatting. No capital letter in the first word & no punctuation 
"-SA1019" # deprecated imports (CARMEN)
```
Imports rue can be enabled once Carmen deprecated API uses are migrated. [TODO](https://github.com/Fantom-foundation/sonic-admin/issues/43)
- errcheck is disabled because of numerous unhandled errors. Manual inspection did not detect any critical issue there, other than the ones already fixed. Nevertheless, it would be convenient to migrate all of them just to be able to enable check automation. 
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint: Enable vet and staticcheck in PR builds

---

evmcore/tx_pool_test.go

The testing of the SampleHashes function in the transaction bool was flaky. In both tests a number of expected transaction were sampled in a loop and it was checked that each of the transaction has been returned at least once and at most the number of samplings.
The order of transactions is random, not all transactions have been returned for each test run. This has simply been fixed by increasing the number of times the sampling is called.
Fixes https://github.com/Fantom-foundation/sonic-admin/issues/40

Fix flaky SampleHashes tests

---

evmcore/dummy_block.go
gossip/blockproc/evmmodule/evm.go
tests/withdrawals_test.go

This PR adds a test that aims to verify the `Withdrawals` field added by ([EIP-4895](https://eips.ethereum.org/EIPS/eip-4895)).
The test:
- sets up a network, looks at the first block and checks that both, the `Withdrawals` list and the Header's `WithdrawalsHash` are empty or nil.
- creates a new block with an empty list of `Withdrawals`, runs RLP enconde/decode and then checks that the decoded list exists but is nil, and the `WithdrawalsHash` is the same as hashing an empty string. 
NOTE: during the development of this test I realized that by default blocks have a `nil` `Withdrawals` slice, which means that the header's `WithdrawalsHash` will be `nil` as well, and this is generates an error when decoding the field, since it expects a `[32]byte` but instead finds an empty string. Should …

Withdrawals verification test

---

evmcore/tx_list_test.go
evmcore/tx_pool.go
evmcore/tx_pool_test.go
gossip/dummy_tx_pool.go
gossip/emitter/config.go
gossip/emitter/emitter.go
gossip/emitter/ordering_test.go
gossip/handler.go
gossip/handler_fuzz.go
gossip/protocols/dag/dagstream/dagstreamleecher/leecher.go
gossip/protocols/dag/dagstream/dagstreamleecher/leecher_test.go
gossip/service.go
gossip/sync.go
gossip/tx_scrambler_test.go
inter/event_serializer_test.go
opera/genesisstore/fileshash/filehash_test.go
topicsdb/topicsdb_test.go
utils/bits/bits_test.go
utils/cser/binary_test.go
utils/fast/buffer_test.go
utils/num_queue_test.go
utils/randat/rand_at.go

Migrate math/rand uses to the v2 version of the API,
This is a non-functional change that replaces the API with its successor. There are 2 main changes:
- Read interface is removed, users of the read functions should use the crypto/rand library. 
- No global Seeding anymore, seed is local to an object and the new Source object requires two uint64 seeds. 
This test migrates all uses to math/rand/v2, and removes uses of Read in tests. Replacing them with loops to reduce the need to include both libraries and having an alias. 
This is one of the 2 deprecated libraries at the moment, the new Carmen API is the other one. 
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/25

Lint: migrate math/rand to v2

---

evmcore/state_processor.go
tests/blob_tx_test.go

This PR adds the modifications needed to allow Blob transactions to proceed into the transaction processor, as long as they do not include Blobs.  
Current implementation would ignore any transaction containing an empty `BlobHashes` field here. Never producing a receipt for such.  [Here](https://github.com/Fantom-foundation/Sonic/blob/09c952eaa6fd6b4b72ed33097f4714275b1e7cd6/evmcore/state_processor.go#L183)
The proposed fix utilizes the same ignore mechanism to drop transactions with blob payload, whilst allowing transactions with empty and nil blob lists.
Blobs are currently being filtered out from submission [here](https://github.com/Fantom-foundation/Sonic/blob/09c952eaa6fd6b4b72ed33097f4714275b1e7cd6/evmcore/tx_pool.go#L661). 
To test the correct execution of blob transaction without …

Allow execution of Blob transactions as long as the carry no Blobs

---

evmcore/dummy_block.go
gossip/gasprice/base_fee.go
gossip/gasprice/base_fee_test.go
inter/time.go

This PR introduces Sonic's base-fee adjustment algorithm. The algorithm is a generalization of the fee market price algorithm described in [EIP-1559](https://ethereum.github.io/abm1559/notebooks/eip1559.html) supporting a variable block-time period.
The maximum increase and decrease is limited to approximately ±12.5% per 15 seconds, analog to Ethereum's implementation.

Add Sonic's base-fee computation algorithm

---

cmd/sonicd/app/launcher.go
config/config.go
config/flags/flags.go
ethapi/api.go
gossip/config.go
gossip/service.go

This PR introduces configurable limit for number of logs, created during debug of EVM with debug namespace
Parameter:
- `rpc.structloglimit `
Default set to 2000 logs

Add configurable structured logs limit for RPC debug

---

gossip/gasprice/gasprice.go
gossip/service.go
tests/integration_test_net.go
tests/integration_test_net_test.go
tests/node_restart_test.go

This PR adds the ability to add tests including the restart of a network node.
Recently, issues have been reported that the restart of a node with local state fails during it startup phase. To address such issues, a new integration test including the restarting of nodes got added. One of the reported issue -- for the node failing to be able to re-load its local transaction pool data -- could be reproduced and fixed as part of this PR.

Add an integration test covering the restart of a node

---

cmd/sonictool/check/archive.go
cmd/sonictool/check/live.go
ethapi/api.go
evmcore/dummy_block.go
evmcore/state_processor.go
gossip/apply_genesis.go
gossip/blockproc/drivermodule/driver_txs.go
gossip/blockproc/evmmodule/evm.go
gossip/blockproc/evmmodule/evm_test.go
gossip/c_block_callbacks.go
gossip/c_llr_callbacks.go
gossip/evm_state_reader.go
gossip/evmstore/store_tx.go
gossip/prevrandao.go
gossip/prevrandao_test.go
gossip/store_block.go
gossip/store_llr_block.go
integration/makefakegenesis/genesis.go
integration/makegenesis/genesis.go
inter/block.go
inter/block_test.go
inter/ibr/inter_block_records.go
tests/block_header_test.go
tests/integration_test_net.go

This PR aligns the block format used by Sonic with the format defined by Ethereum. In particular, hashes to identify blocks are now equivalent to the hashes of the respective block headers.
**Note:** this PR breaks backward compatibility with the Fantom mainnet. After this change, genesis data of former Fantom networks can no longer be used and resulting block hashes are incompatible.
The main change required for this is the re-design of the storage format of blocks as they are retained on the disk. The previous format was a summary of the consensus events that formed to block, in particular including the list of `Events` the block was created from, as well as the Atropos and various lists of transactions and flags composing the block. When block information was required, it was derived …

Use block-header hashes to address blocks

---

evmcore/tx_pool.go
tests/transaction_gas_price_test.go

This PR adds tests for the fields `max_fee_per_gas`,  `max_priority_fee_per_gas` in dynamic fee transactions (Type 1, eip-1559) and `gasPrice` in legacy transactions (type 0).
All transactions have the following properties:
- balance is reduced by an amount of gas equal to `effectiveGasPrice * transactionGasCost`
Dynamic pricing transactions have the following properties:
- `effectiveGasPrice` is equal to `baseFee + Tip`
- `baseFee <= effectiveGasPrice <= MaxGasFee`
- `baseFee + Tip == MaxGasFee` ⇆  `Tip < MaxTip`  (tipping will not exceed the maximum price allowed) 
Legacy transactions have the following properties: (section Backwards Compatibility in [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559))
- `effectiveGasPrice` is equal to `GasPrice` specified in transaction. 
- …

Add integration test for transaction gas prices.

---

gossip/gasprice/base_fee.go
gossip/gasprice/base_fee_test.go
opera/rules.go

This PR introduces a dedicated `MinBaseFee` parameter into the `EconomyRules` to control the minimum base fee in a network.
This eliminates the overloaded semantic of the preexisting `MinBaseFee`. 
It also eliminates interference of (outdated) SFC gas-price updates emitted at the end of each epoch with the new per-block base-fee pricing. This as been encountered as an obstacle when trying to test the new base-fee pricing model in fake-nets and experimental nets in Norma.

Introduce dedicated min-base-fee parameter into rules

---

ethapi/api.go
evmcore/state_processor.go

This PR adds possibility to debug **non historical** transactions. Similar to `eth_call` function, `debug_traceCall` function can run a transaction with EVM and obtain result and traces of the EVM run.
Added function:
- `debug_traceCall`
Refers to https://github.com/Fantom-foundation/sonic-admin/issues/54

Add debug_traceCall RPC function

---

evmcore/dummy_block.go
gossip/apply_genesis.go
gossip/blockproc/evmmodule/evm.go
gossip/blockproc/evmmodule/evm_test.go
gossip/c_block_callbacks.go
gossip/c_llr_callbacks.go
integration/makegenesis/genesis.go
inter/block.go
tests/address_access_test.go
tests/block_header_test.go

This PR integrates Sonic's base-fee adjustment algorithm into the Sonic client. After this PR, base-fees are updated with each block and no longer determined at the epoch boundary.
To integrate this feature, two additional values need to be stored in blocks:
- the nano-second part of the block **time**, using 4 bytes
- the **block duration**, defined as the duration in nanoseconds between the a block's predecessor and the block itself (8 bytes)
Both values are required for the computation of base-fee prices. Since fields can not be arbitrarily added to blocks, a pre-existing, previously unused 32-byte "extra-data" fields was used. The two new values are stored in big endian format in the first 12 bytes of this value.
Besides these changes, this PR also fixes the handling of the `GasLimit` …

Integration of Sonic's per-block base-fee adjustment

---

tests/contracts/counter_event_emitter/counter_event_emitter.go
tests/contracts/counter_event_emitter/counter_event_emitter.sol
tests/transaction_order_test.go

Extends the transaction order test to verify the total order of transactions and the correct association between transactions and receipts.

Extend transaction order test to cover total order of transactions

---

ethapi/api.go
ethapi/tx_trace.go

This PR adds possibility to generate transaction traces for non historical transactions. Similar to eth_call function, trace_call function can run a transaction with EVM and obtain inner contract calls in form of transaction traces of the EVM run.
Added function:
- `trace_call`
There are 3 possible trace types. For now only `trace` is implemented, `vmTrace` and `stateDiff` will be implemented in following PRs.
Refers to https://github.com/Fantom-foundation/sonic-admin/issues/55

Introduce trace_call RPC function

---

evmcore/dummy_block.go
gossip/blockproc/evmmodule/evm.go

Norma depends on the proper reporting of the epoch a block belongs for its logging and debugging. 
Before #301 this epoch information was extracted from a block's hash. Now, since this information is no longer encoded in the hash, an alternative source is required. This PR adds explicit tracking of epoch information.

Fix recording and reporting of epoch information in blocks

---

gossip/c_block_callbacks.go

This PR brings back the epoch number to the `NewBlock` logging.

Bring back epoch logging

---

go.mod
go.sum

This PR updates Carmen to include this fix: https://github.com/Fantom-foundation/Carmen/pull/1049
It fixes `HasEmptyStorage` method on `stateDB` to return a correct value if an account is self destructed and re-created within the same block.  Originally,   `HasEmptyStorage`  has seen only the state from previous block. If the self-destruct was called, the storage must be considered empty, but the method would reflect it and prevented re-creation of the account. 
With this change, the method  `HasEmptyStorage` checks changes happening in current block and reflects that a desctructed account has an empty storge.
TODO

updates Carmen - fix to HasEmptyStorage for self-destruct acc

---

gossip/c_block_callbacks.go
tests/block_header_test.go

This PR fixes association of blocks to epochs.
Before this PR, blocks concluding an epoch got incorrectly associated to the newly started epoch. After this change, blocks sealing an epoch are the last block within the sealed epoch.
For the issue to be revealed, block information must be read from the store -- not from an in-memory cache of block information that is internally used to speed up RPC requests of recent blocks. Thus, to discover such caching issues also in potential other contexts, the header-invariant test was extended to include a node-restart step.

Correct epoch number in block data

---

gossip/c_block_callbacks.go
gossip/common_test.go
gossip/emitter/control.go
gossip/emitter/control_test.go
gossip/emitter/emitter.go
gossip/emitter/hooks.go
opera/rules.go
tests/block_header_test.go
tests/gas_price_suggestion_test.go

This PR introduces a simplification of the event emitter timing policy. The previous emitter policy which was deriving the decision whether to emit or not from various network-state parameters is (optionally) replaced by a simpler time-based emitter rate.
If enabled, the new emitter has the following properties:
- in normal mode, every validator produces a new event every `X` milliseconds
- if for threshold time `T` no new events are confirmed on the network, the emitter switches into a `stall` mode and reduces the emitter rate to `Y`
The parameters `X`, `T`, and `Y` can be configured using network rules. Those rules also allow to disable this rate-based emitter policy and revert to the previous policy.
In Norma based experiments, this new emitter timing policy helps reducing block-time …

Switch to fixed emitter rate

---

ethapi/api.go
ethapi/backend.go
ethapi/mock_backend.go
gossip/ethapi_backend.go
gossip/gasprice/constructive.go
gossip/gasprice/gasprice.go
gossip/gasprice/gasprice_test.go

Removes the method `ftm_effectiveBaseFee` from the list of supported RPC methods. 
This method is nowhere documented and introduces complexity that restricts refactoring and other improvements. For instance, it blocks #326 due to the difficult interaction of network rules with those base-fee predictions.
Furthermore, this function's implementation seems to be wrong. For anybody to obtain the effective base fee, a simple query of the current block head would be sufficient. This head includes the current base fee.

Remove unnecessary effective base-fee method

---

.github/workflows/test_build.yml
integration/makegenesis/genesis.go
tests/block_header_test.go

This PR adds a check verifying that the state roots reported by blocks match the state roots stored in the database.
It does so by extracting witness proofs for account states on each block and verify that those proofs are rooted by a corresponding node.
While doing so, an issue regarding the initialization of archives during genesis imports has been discovered and fixed.

Add check of state-root hash consistency

---

.github/workflows/test_build.yml

Tests are currently too large for GH, tests are checked by Jenkins. 
GH would test compilation of unit tests, but it will not run them.

Remove unit tests from github actions

---

ethapi/api.go
tests/blob_tx_test.go

To support type 3 (blob) transactions, these two missing fields need to be included in the serialization.
This missing fields triggered an error during the deserialization when fetching the last block, after a blob tx was executed.

Add missing blob fields to rpc json serialization

---

cmd/sonicd/app/launcher.go
cmd/sonicd/app/run_test.go
cmd/sonictool/app/chain.go
cmd/sonictool/app/export_genesis.go
cmd/sonictool/app/genesis.go
cmd/sonictool/app/main.go
cmd/sonictool/chain/export_events.go
cmd/sonictool/db/dbutils.go
cmd/sonictool/genesis/import.go
config/flags/flags.go
tests/integration_test_net.go

This PR lowers memory usage for fake net and integration tests by ~500 MB per test.
Before:
After:
part of https://github.com/Fantom-foundation/sonic-admin/issues/50

Lower integration tests memory usage

---

tests/block_header_test.go

This PR adds an end-to-end test for witness proofs. As a side-effect, this test also cross-checks the reported state roots in blocks.

Add test verifying witness proof support

---

tests/block_header_test.go
tests/integration_test_net.go

This change isolates each instance of an integration test by choosing a different (best-effort unused) set of ports, and turning off discovery protocol.
Although tests are currently not segregated, this PR enables the segregation of those into different processes, this change is currently waiting for the memory usage reduction.
This test enables developers to locally run multiple integration tests simultaneously.

Generate different ports for each integration test net.

---

evmcore/state_processor.go
evmcore/state_processor_test.go
gossip/blockproc/evmmodule/evm.go
gossip/c_block_callbacks.go
tests/block_header_test.go

This PR fixes an issue discovered by @jenikd: when querying for log events by index-topic, the wrong block hash is reported.

Fix the block hash listed by log messages stored in the index table

---

gossip/c_block_callbacks.go
tests/block_header_test.go

This PR also adds an update of the block hash inside the receipt as soon as the block completes.
It does not seem like the missing block-hash set in `c_block_callbacks.go` was actually used by anybody, since all tests passed already before. However, in the spirit of defensive coding this value should be set to avoid potential future mistakes.

Set correct block-hash in receipts after finishing the block

---

go.mod
go.sum

This PR updates Carmen version to `34dad37b56481fcd1863d93cd501278420a1e265` which contains Cache capacity changes for `Export/ImportLiveDb` which lowers memory consumption in `integration_tests` by ~1.1GB
Before:
After:
Part of https://github.com/Fantom-foundation/sonic-admin/issues/50

Update Carmen version

---

ethapi/api.go
go.mod
go.sum
tests/block_header_test.go

Updates Carmen version to deliver witness proof steps in trie-navigation order.
TODO:

Update Carmen to get proof steps in correct order

---

tests/gas_price_suggestion_test.go
tests/rejected_tx_test.go

This PR solves https://github.com/Fantom-foundation/sonic-admin/issues/84
A test it added that specifically verifies that transactions are rejected if the signing account does not have enough balance to pay for `transferred value + gas_limit * max_fee_cap`. This is tested for all 4 types of transactions. 
The test uses a slice of Tx instead of a map because of the issue fixed in #346

Add integration test for rejected transactions because of insufficient balance

---

tests/integration_test_net.go
tests/log_subscription_test.go

This PR adds an initial test to verify that subscribing for log events through the web-socket interface is supported.
Tests that should follow:
- check that filter criteria are supported
- check that subscriptions for new head-blocks is working
- check proper isolation between multiple subscriptions
- ...

Add a test checking the support for subscribing to log events

---

ethapi/api.go
ethapi/api_test.go

This PR fixes RPC method `GetProof` such that it uses data from already extracted proof instead of calling the state again.

Use data from proof.

---

gossip/handler.go
gossip/protocols/dag/dagstream/dagstreamleecher/leecher.go

This PR disables the requesting of event payload data when streaming events from other nodes.
Receiving messaged from a stream of events with payload currently leads to a message parsing error, causing the peer connection used for streaming those events to be disconnected. After a time-out of a few seconds, another attempt for streaming events is started -- however in the second attempt only event IDs are fetched, which then succeeds.
During syncing, this effect can be observed by the process seemingly freezing between epochs for a few seconds. With this fix, this effect disappears.
Besides disabling requests of event streams with payload, this PR also upgrades the reporting of communication issues to the log-level of a warning to allow issues like this to be detected more easily in the …

Skip fetching event payloads when streaming events

---

cmd/sonicd/app/launcher.go
cmd/sonicd/app/run_test.go
cmd/sonictool/app/genesis.go
cmd/sonictool/app/main.go
config/config.go
config/flags/flags.go
gossip/common_test.go
gossip/evmstore/config.go
gossip/evmstore/store.go
gossip/handler_fuzz.go
integration/makefakegenesis/genesis.go
integration/makefakegenesis/json.go
integration/makegenesis/genesis.go
tests/integration_test_net.go

This PR lowers memory consumption by fakenet and integration tests by StateDB instances by ~250 MB
Before
After:
part of https://github.com/Fantom-foundation/sonic-admin/issues/50

Lower memory consumption for integration tests.

---

ethapi/api.go
ethapi/api_test.go
tests/get_account_test.go

This PR adds getAccount method to the RPC according to [this](https://www.quicknode.com/docs/ethereum/eth_getAccount) documentation.
Copy of #317 - `StorageRoot` can now be extracted from `WitnessProof`

Implement getAccount RPC method

---

utils/caution/caution.go
utils/caution/caution_test.go

This PR adds a utility lib that calls a function and reports whether it returned an error or not.
The function `CloseAndReportError` is meant to facilitate the check and handle of closing resources, which is one of the main unhandled errors across the code base. As we work on fixing unhandled errors (which are mostly unlikely to fail or coming from non-logical issues). 
part of https://github.com/Fantom-foundation/sonic-admin/issues/90

Caution package

---

cmd/cmdtest/test_cmd.go
cmd/sonicd/app/run_test.go
evmcore/tx_pool_test.go
gossip/basiccheck_test.go
gossip/c_block_callbacks_test.go
gossip/common_test.go
gossip/evm_test.go
gossip/heavycheck_test.go
gossip/sfc_test.go
opera/genesisstore/fileshash/filehash_test.go
tests/block_hash_test.go
tests/integration_test_net.go
tests/selfdestruct_test.go
topicsdb/topicsdb_test.go
utils/dbutil/compactdb/keys_test.go
utils/fast/buffer_test.go

This PR add error handling in unit tests for every test file in the project. 
This PR does not change code used anywhere but tests. 
Part of: https://github.com/Fantom-foundation/sonic-admin/issues/90

Handle every error in test routines

---

utils/errlock/errlock.go

This PR restricts the file-permission of error log file.
This issue was identified by an external audit and was classified at a medium risk level. In its old state it would allow malicious local users on the system to inject messages that would get displaced to the user of the `sonicd` application.

Restrict access to errlock file

---

ethapi/transaction_args.go
ethapi/transaction_args_test.go

This PR fixes gas cap of the RPC requests. Because of [Tosca](https://github.com/Fantom-foundation/Tosca/blob/4da02eca5a6c16bfcec36c1c401957cab71b8e57/go/tosca/interpreter.go#L137) maximum gas has to be limited to MaxInt64. If it was higher, the EVM immediately failed because of out of gas.

RPC gas capping
