Fantom-foundation/Sonic

cmd/sonictool/main.go, config/config.go
Add missing --flag for events import.
=> Add --mode flag to sonictool import events

gossip/handler.go, gossip/handler_test.go, version/version.go
* Increase the client version to be considered newer than any Opera client
* Fix peers filtering
=> Fix peers filtering, increase the version

ethapi/tx_trace.go
Use function
`evmcore.ApplyTransactionWithEVM`
instead of 
`evmcore.ApplyMessage`
for replaying transactions with EVM
=> Use new function for replaying transaction

inter/ibr/block_record_rlp_test.go
Follow-up of #132 - prove that nil Topics are not issue of genesis files.
=> Verify that nil Topics in log does not propagate into genesis

go.mod, go.sum
Include https://github.com/Fantom-foundation/go-ethereum-substate/pull/58
=> Warn when dialing static peer fails

cmd/sonictool/chain/export_genesis.go
Genesis exporter now exports only the last epoch of blocks for validator's genesis, however EVM ops allows to ask for last 256 blocks. At least last 256 block should to be included in every genesis.
=> Include last 256 blocks into validators genesis

version/version.go
Tag new version:
* new supported genesis files
* added dagIndexer cache
=> Tag Sonic-1.2.1-c

Dockerfile
Use Debian-based golang docker base image instead of the alpine one.
=> Update Dockerfile to use Debian instead of Alpine

ethapi/api.go
Checking reference for message to variable and using recover for this tracetx function
=> Fix message to reference

cmd/sonictool/export_genesis.go, cmd/sonictool/genesis/allowed.go, cmd/sonictool/genesis/export.go, cmd/sonictool/genesis/import.go, cmd/sonictool/genesis/sign.go, cmd/sonictool/genesis/signature.go, cmd/sonictool/main.go, cmd/sonictool/sign_genesis.go, opera/genesis/types.go, opera/genesisstore/store_genesis.go
Add new genesis section with EIP-712 signature of other sections hashes.
Allows to release new genesis files without modifying codebase.
=> Add SignatureSection into genesis

ethapi/api.go
This adds StateDB releasing into several places, where StateDB is obtained, but not released correctly.
=> Fix StateDB releasing in debug api

cmd/sonictool/check/archive.go, go.mod, go.sum, gossip/evmstore/statedb_import.go, gossip/evmstore/statedb_verify.go, integration/makegenesis/genesis.go
Reverting Carmen upgrade back to version used in release v1.2.1-d.
=> Downgrade to Carmen version from 1.2.1-d

version/version.go
To be merged after https://github.com/Fantom-foundation/Sonic/pull/174 !
=> Tag Sonic-1.2.1-e

cmd/sonictool/genesis/export.go
Include 32768 epochs (MaxLiableEpochs) into exported validator genesis file.
This partially reverts #142.
=> Export MaxLiableEpochs into validator genesis

go.mod, go.sum, gossip/evmstore/carmen.go, gossip/evmstore/statedb_import.go
This PR updates the development branch to the latest version of Carmen.
This is required to resolve dependency issues when testing Carmen with Aida.
=> Update Carmen to latest version

demo/_params.sh, demo/start.sh, demo/stop.sh
Update old scripts for running demo network to work with Sonic.
=> Update demo scripts for Sonic

go.mod, go.sum, gossip/evmstore/statedb_import.go
this PR updates to the newest carmen import API
=> upgrades to latest carmen import api

cmd/sonictool/check/archive.go, cmd/sonictool/check/live.go, go.mod, go.sum, gossip/evmstore/statedb_verify.go
This PR update `develop` branch to Carmen version `3fc9e177f6bb15f517db30573f9b50266706de04` and fixing verify function calls.
=> Update Carmen version, fix incorrect parameters.

version/version.go
Update the version string (we should consider re-creating the tag)
=> Tag Sonic-1.2.1-g

gossip/protocols/dag/dagstream/dagstreamleecher/leecher.go
Updated version of #154 - optimize the leecher peer selection process.
=> Optimize peer selection for initial events download

tests/counter_test.go
This PR adds an end-to-end integration test for the following features:
- deploy a contract
- run state updates on contract and check that effects are observable on the head state
- run state updates and check that effects are observable in the block history
This is part of [#7](https://github.com/Fantom-foundation/sonic-admin/issues/7).
=> Add integration tests for state updates and historic state queries

ethapi/tx_trace.go
This PR is the same as https://github.com/Fantom-foundation/Sonic/pull/268, but this is for develop branch
=> Fix error handling for trace, duplicate of #268 for dev branch

Jenkinsfile
This PR merges change from develop branch to include `Jenkinsfile` for CI merge check
=> Adds jenkinsfile

ethapi/tx_trace.go
This PR fixes situation, when requested transaction is not available for tracing and wrong message was returned
=> Fix error handling for trace

gossip/gasprice/base_fee.go, gossip/gasprice/base_fee_test.go
This PR adds a configurable lower limit to the base-fee gas price. Prices will not sink below this value.
=> Add support for a minimum base fee configuration option

gossip/c_block_callbacks.go, gossip/tx_scrambler.go, gossip/tx_scrambler_test.go
This PR integrates previously created `txScrambler` into block processing.
=> Integrate tx scrambler

gossip/apply_genesis.go, gossip/store_llr_block.go, integration/makefakegenesis/genesis.go, integration/makegenesis/genesis.go, inter/ibr/inter_block_records.go
Introduces the creation of a valid block 0 which results in all tests being passed.
=> Create explicit block 0 in genesis data

cmd/sonicd/app/misccmd.go, gossip/c_block_callbacks.go, gossip/common_test.go, gossip/config.go, gossip/handler.go, gossip/peer.go, gossip/protocol.go, gossip/service.go, gossip/topology/connection_advisor.go, gossip/topology/connection_advisor_test.go
This PR extends the Fantom P2P protocol with new functionality to retrieve connection information from peers. This information is then used to establish connections to new peers and eliminate redundant connections to improve the overall network connectivity and minimize the network diameter.
=> Add heuristic to reduce network diameter

Jenkinsfile, example-genesis.json, integration/makefakegenesis/genesis.go, integration/makefakegenesis/json.go, integration/makegenesis/genesis.go, tests/block_header_test.go, tests/integration_test_net.go
This PR adds an integration test checking the proper support for initiating the client state using a JSON genesis file.
=> Add integration test for JSON Genesis

tests/block_header_test.go, tests/integration_test_net.go
This PR adds an integration test verifying that log messages can be retrieved from the chain even after node restarts and re-initialization.
=> Check completeness of logs

tests/block_hash_test.go, tests/contracts/block_hash/block_hash.go, tests/contracts/block_hash/block_hash.sol, tests/contracts/block_hash/gen.go
Adds a test verifying that the correct block hashes are obtainable within the EVM.
=> Add integration test checking block hashes reported inside the EVM

gossip/ethapi_backend.go
This PR is a copy of https://github.com/Fantom-foundation/Sonic/pull/373 which was already merged to main branch
=> Handle finalized and safe tags for block number in RPC requests

gossip/ethapi_backend.go
This PR is a copy of https://github.com/Fantom-foundation/Sonic/pull/374 which was already merged into main branch
=> Fix error propagation for header functions

Jenkinsfile
This PR is reintroducing missing Jenkinsfile configuration to allow Jenkins to run CI tests as intended.
=> Reintroduce jenkinsfile configuration for ci/ct
